const audio=document.querySelector('#beat'),play=document.querySelector('#play'),pause=document.querySelector('#pause'),player=document.querySelector('#player'),seek=document.querySelector('#seek'),time=document.querySelector('#time');
const fmt=s=>`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`;
function sync(){if(!Number.isFinite(audio.duration))return;seek.max=audio.duration;seek.value=audio.currentTime;time.textContent=`${fmt(audio.currentTime)} / ${fmt(audio.duration)}`;pause.textContent=audio.paused?'▶':'Ⅱ';document.querySelector('#flPlay').classList.toggle('active',!audio.paused)}
play.addEventListener('click',()=>{audio.play();player.classList.add('show')});pause.addEventListener('click',()=>audio.paused?audio.play():audio.pause());document.querySelector('#flPlay').addEventListener('click',()=>audio.paused?audio.play():audio.pause());document.querySelector('#flBack').addEventListener('click',()=>{audio.currentTime=0;sync()});audio.addEventListener('timeupdate',sync);audio.addEventListener('loadedmetadata',sync);audio.addEventListener('play',sync);audio.addEventListener('pause',sync);seek.addEventListener('input',()=>audio.currentTime=+seek.value);
document.querySelector('#restaurant').addEventListener('click',()=>document.querySelector('#restaurantSecret').classList.toggle('show'));
const channelData=[['KICK',[0,4,8,12]],['CLAP',[4,12]],['HAT',[2,6,10,14]],['808',[0,3,7,8,11,15]],['ASHER',[1,5,9,13]]];const channels=document.querySelector('#channels');channelData.forEach(([name,on])=>{const row=document.createElement('div');row.className='channel';const lab=document.createElement('label');lab.textContent=name;row.append(lab);for(let i=0;i<16;i++){const b=document.createElement('button');b.type='button';b.className='step'+(on.includes(i)?' on':'');b.setAttribute('aria-label',`${name} step ${i+1}`);b.addEventListener('click',()=>b.classList.toggle('on'));row.append(b)}channels.append(row)});
const reasons=['Your dimples.','Your green-blue eyes.','How gentle you are with me when I cry.','The way you call me sweetheart.','How passionate you are about music.','Watching you make a beat from start to finish.','How deeply you think about movies.','Your style.','Your bathtub selfies.','Walking Bodhi with you.','Our calls.','How patient you are with me.','How much I learn from you.','Your need to crack my fingers.','And my toes, apparently.','The fact that you made “valid” part of my vocabulary.','Your Star Wars obsession.','How much you like LEGO.','How comfortable I feel around you.','How caring you are when I’m emotional.','That we found our way back to each other.'];const grid=document.querySelector('#reasons'),out=document.querySelector('#reasonOutput');reasons.forEach((x,i)=>{const b=document.createElement('button');b.type='button';b.className='reason';b.textContent=String(i+1).padStart(2,'0');b.addEventListener('click',()=>{grid.querySelectorAll('.reason').forEach(n=>n.classList.remove('active'));b.classList.add('active');out.textContent=x});grid.append(b)});
const extras={star:'I like how genuinely into Star Wars you are. There is something very cute about hearing you talk about the things you know way too much about.',comic:'Taking you to BMV and watching you leave with Superman and Batman comics made me very happy. Extremely successful bookstore trip.',office:'I still think your relationship with the word “valid” deserves its own Dundie.',lego:'I like that you can be into producing and underground music and still just really like LEGO. Range.'};document.querySelectorAll('[data-extra]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-extra]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#extraOutput').textContent=extras[b.dataset.extra]}));
document.querySelector('#openLetter').addEventListener('click',e=>{document.querySelector('#letterBody').classList.add('show');e.currentTarget.style.display='none'});document.querySelector('#oneMore').addEventListener('click',()=>document.querySelector('#punchline').classList.toggle('show'));
