const $=s=>document.querySelector(s),audio=$('#beat'),vinyl=$('#vinyl'),player=$('#player'),play=$('#play'),pause=$('#pause'),seek=$('#seek'),time=$('#time');
const fmt=n=>`${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`;
play.addEventListener('click',async()=>{player.classList.add('show');try{await audio.play();vinyl.classList.add('spinning');pause.textContent='Ⅱ'}catch(e){pause.textContent='▶'}});pause.addEventListener('click',async()=>{if(audio.paused){await audio.play();vinyl.classList.add('spinning');pause.textContent='Ⅱ'}else{audio.pause();vinyl.classList.remove('spinning');pause.textContent='▶'}});audio.addEventListener('timeupdate',()=>{seek.value=audio.currentTime;time.textContent=`${fmt(audio.currentTime)} / ${fmt(audio.duration||198.391)}`});audio.addEventListener('ended',()=>{vinyl.classList.remove('spinning');pause.textContent='▶'});seek.addEventListener('input',()=>audio.currentTime=Number(seek.value));
$('#restaurant').addEventListener('click',()=>$('#restaurantSecret').classList.toggle('show'));
const channels=[['KICK',[0,4]],['SNARE',[2,6]],['808',[0,3,4,7]],['FX',[1,5]]],seq=$('#sequencer');channels.forEach(([name,on])=>{const row=document.createElement('div');row.className='seq-row';row.innerHTML=`<label>${name}</label>`;for(let i=0;i<8;i++){const p=document.createElement('button');p.type='button';p.className='pad'+(on.includes(i)?' on':'');p.setAttribute('aria-label',`${name} step ${i+1}`);p.addEventListener('click',()=>p.classList.toggle('on'));row.appendChild(p)}seq.appendChild(row)});
const lore={star:'<div class="crawl">A LONG TIME AGO, IN A HINGE APP FAR, FAR AWAY…<br><br>somehow you kept replying until I finally stopped being difficult.</div>',comic:'<div class="comic-pop">POW! BMV SIDE QUEST UNLOCKED.</div><p>Superman + Batman acquired. Girlfriend bookstore recommendation successful.</p>',office:'<div class="dundie">🏆<strong>THE 2026 DUNDIE</strong><span>Most Likely to Say “Valid” in a Suspicious Tone</span></div>',lego:'<p><b>BUILD STATUS: IN PROGRESS.</b><br>Current pieces include music, movies, Bodhi walks, long calls, comics, random jokes, and whatever we add next.</p>'};document.querySelectorAll('[data-lore]').forEach(b=>b.addEventListener('click',()=>$('#loreOutput').innerHTML=lore[b.dataset.lore]));
const reasons=["Your dimples. Obviously.","Your eyes, that green-blue colour is actually unfair.","How gentle you are with me when I cry.","The way you call me sweetheart.","How passionate you are about music.","Watching you make a beat from start to finish.","How deeply you think about movies.","Your style.","Your random bathtub selfies.","Walking Bodhi with you.","Our basically-every-day calls.","Your patience with me.","How much I learn from you.","Your obsession with cracking my fingers.","The fact that you made ‘valid’ part of my vocabulary.","Your love for Star Wars.","Your love for LEGO.","How comfortable I feel around you.","How caring you are when I'm emotional.","How you make ordinary days feel special.","That after everything, we found our way back to each other."];const grid=$('#reasons'),out=$('#reasonOutput');reasons.forEach((r,i)=>{const b=document.createElement('button');b.type='button';b.textContent=String(i+1).padStart(2,'0');b.addEventListener('click',()=>{b.classList.add('revealed');b.textContent='♡';out.textContent=r});grid.appendChild(b)});
document.querySelectorAll('[data-future]').forEach(b=>b.addEventListener('click',()=>{$('#future').textContent=`Future slot unlocked: ${b.dataset.future}. ♡`;b.querySelector('span').textContent='UNLOCKED'}));$('#openLetter').addEventListener('click',e=>{$('#letter').classList.add('show');e.currentTarget.style.display='none'});$('#oneMore').addEventListener('click',()=>$('#punchline').classList.toggle('show'));

// subtle reference easter eggs
const refMessages={force:'STAR WARS // birthday transmission received. The force is suspiciously strong with this one.',panels:'MARVEL // Issue #21: Asher enters his next era. BMV side quest already completed.',dunder:'DUNDER MIFFLIN // Award: Most Likely to Say “valid” in a Tone That Needs Further Investigation.',studs:'LEGO // No plastic bricks on the page. Just a reminder that the good stuff gets built one piece at a time.'};
document.querySelectorAll('[data-ref]').forEach(btn=>btn.addEventListener('click',()=>{const out=document.getElementById('refOutput');out.textContent=refMessages[btn.dataset.ref]||'';}));
